image: node:16.5.0

pages:
  stage: deploy
  script:
    - mkdir public
    - find . -maxdepth 1 -not -name 'public' -exec cp -r {} public/ \;
  artifacts:
    paths:
      - public
  only:
    - master


